name = "cloudflare-d1-example"
main = "src/index.ts"
compatibility_date = "2023-04-18"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "cloudflare-d1-example"
database_id = "f2021ad1-584a-4b6f-aac7-8827d0e695fc"
